#ifndef _CONFIGURATION_H
#define _CONFIGURATION_H

#define TIME_MIN_MAX_MIXER_MS 5000
#define INITIAL_TEMPERATURE 20
#define STEPS 20
#define TIME_FOR_STEP_MS TIME_MIN_MAX_MIXER_MS/STEPS
#define STEP_SIZE 100/STEPS
#define MIN_DELTA_INLET_OUTLET_DEG 2
#define WAIT_BETWEEN_CHANGES_OF_REGULATION_MS 10000
#define TEMPERATURE_CORRECTION 0

#endif
