#define TIME_MIN_MAX_MIXER_MS 20000;
#define INITIAL_TEMPERATURE 20;
#define STEPS 20;
#define TIME_FOR_STEP_MS TIME_MIN_MAX_MIXER_S/STEPS;
#define STEP_SIZE 100/STEPS;
#define MIN_DELTA_INLET_OUTLET_DEG 1;
#define MAX_INLET_TEMP 30;
#define WAIT_BETWEEN_CHANGES_OF_REGULATION_MS 10000;
